"""Constants and exit codes for Personal Tideway."""

from enum import IntEnum


class ExitCode(IntEnum):
    """Documented exit codes for Personal Tideway CLI."""
    SUCCESS = 0
    VALIDATION_ERROR = 1
    CONFIG_ERROR = 2
    CONFLICT = 3
    RUNTIME_PROBE_ERROR = 4


SCHEMA_VERSION = 2

RULE_MARKER_START = "<!-- PERSONAL-TIDEWAY:START -->"
RULE_MARKER_END = "<!-- PERSONAL-TIDEWAY:END -->"

CLIENT_CODEX = "codex"
CLIENT_AGY = "agy"
SUPPORTED_CLIENTS = (CLIENT_CODEX, CLIENT_AGY)

TRANSPORT_STDIO = "stdio"
TRANSPORT_HTTP = "http"
SUPPORTED_TRANSPORTS = (TRANSPORT_STDIO, TRANSPORT_HTTP)

SKILL_LINK_SYMLINK = "symlink"
SKILL_LINK_COPY = "copy"
SUPPORTED_SKILL_LINK_MODES = (SKILL_LINK_SYMLINK, SKILL_LINK_COPY)

DEFAULT_PERSONAL_TIDEWAY_DIR = ".personal-tideway"
DEFAULT_CONFIG_YAML = "config.yaml"
DEFAULT_SECRETS_ENV = "secrets.env"  # pragma: allowlist secret
DEFAULT_STATE_FILE = "state.json"

PROJECT_KIND_GIT = "git"
PROJECT_KIND_DIRECTORY = "directory"
PROJECT_KIND_EXTERNAL = "external"
SUPPORTED_PROJECT_KINDS = (PROJECT_KIND_GIT, PROJECT_KIND_DIRECTORY, PROJECT_KIND_EXTERNAL)

DEFAULT_MEMORY_BACKEND = "basic-memory"
SUPPORTED_MEMORY_BACKENDS = (DEFAULT_MEMORY_BACKEND,)

CONTINUITY_RULE_FILENAME = "continuity.md"
CONTINUITY_SKILL_NAME = "continuity"

ASSURANCE_LEVEL_HOOKED = "hooked"
ASSURANCE_LEVEL_INSTRUCTED = "instructed"
ASSURANCE_LEVEL_MANUAL = "manual"
ASSURANCE_LEVEL_UNAVAILABLE = "unavailable"
SUPPORTED_ASSURANCE_LEVELS = (
    ASSURANCE_LEVEL_HOOKED,
    ASSURANCE_LEVEL_INSTRUCTED,
    ASSURANCE_LEVEL_MANUAL,
    ASSURANCE_LEVEL_UNAVAILABLE,
)

HOOK_STATUS_INSTALLED = "installed"
HOOK_STATUS_NOT_INSTALLED = "not-installed"
HOOK_STATUS_CONFLICT = "conflict"
SUPPORTED_HOOK_STATUSES = (
    HOOK_STATUS_INSTALLED,
    HOOK_STATUS_NOT_INSTALLED,
    HOOK_STATUS_CONFLICT,
)

AGY_HOOK_NAME = "personal-tideway"
AGY_HOOK_EVENT = "PreInvocation"
AGY_HOOK_COMMAND = "ptw hook agy-preinvocation"
AGY_HOOK_TIMEOUT = 30
MAX_HOOK_INPUT_BYTES = 64 * 1024  # 64 KiB conservative cap
MAX_HOOKS_JSON_BYTES = 256 * 1024  # 256 KiB conservative cap for hooks.json
